# Generated by Django 5.1.1 on 2024-11-18 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
